id: 503bf0f960a9456c95f852fc8d58c114
initial_creation_type: ocr
source_metadata:
  volumes:
    c7c744322c9d4ef9965ea6682edc56dc:
      base_file: v115.txt
      image_group_id: I1PD95961
      title: རིགས་ཀྱི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
