id: D706678E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:44:02+00:00'
last_modified: '2022-05-30T06:34:11.795861+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9b24:
      image_group_id: I1PD95961
      title: རིགས་ཀྱི་སྨོན་ལམ།
      total_pages: 1880
      order: 116
      base_file: 9b24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
